env:
  RESOURCE_GROUP: aguadamillas_students_1
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: ketis

on: [push]

name: Build_and_Publish_to_ACR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.DOCKER_REGISTRY_SERVER_URL }}
          username: ${{ vars.DOCKER_REGISTRY_SERVER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      - name: Set image version
        id: image-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build . -t ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/flask-demo:${{ steps.image-version.outputs.version }}
          docker build . -t ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/flask-demo:${{ github.ref_name }}-latest
          docker push ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/flask-demo:${{ steps.image-version.outputs.version }}
          docker push ${{ vars.DOCKER_REGISTRY_SERVER_URL }}/flask-demo:${{ github.ref_name }}-latest
